name: liquid_ui
description: Liquid is an open source UI toolkit for developing cross platform apps using Flutter.

version: 1.0.0-beta+1

repository: https://github.com/stackorient/Liquid
homepage: https://github.com/stackorient/Liquid

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.18.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
